# Generated by Django 3.2.6 on 2021-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sched_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sched_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
